name: funday_download_media_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  provider: ^6.1.1
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  just_audio: ^0.9.35
  path: ^1.8.3
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
